### Introduction to Python
#### Date: Sep 06,2023
#### Submission must be made through Github
You are required to complete all tasks correctly (or almost correctly) . You are free to use any material (lecture, Stackoverflow etc.) except full solutions but you should first try to figure them out on your own. We use an nbgrader for partially autograding the assignments. Please DO NOT delete or copy cells. You can add new cells but your solutions should go into the designated cells. 

`range()` practice

1 . Print the numbers between 60 and 69 inclusive.

In [2]:
import numpy as np

In [1]:
# YOUR CODE HERE
numbers = list(range(60,70))
print(numbers)
# raise NotImplementedError()

[60, 61, 62, 63, 64, 65, 66, 67, 68, 69]


2 . Read numbers until 0 and print their mean and standard deviation without using a list.

In [14]:
# YOUR CODE HERE
import math

total = 0
sum_of_squares = 0
count = 0

while True:
    number = float(input("Enter a number: "))
    if number == 0:
        break
    total += number
    sum_of_squares += number ** 2
    count += 1

mean = total / count if count > 0 else 0

if count > 1:
    std_deviation = math.sqrt((sum_of_squares - (total ** 2 / count)) / (count - 1))
else:
    std_deviation = 0

print("\n" + "The Mean is: " + str(mean) + "\n")
print("The Standard Deviation is : " + str(std_deviation))
# raise NotImplementedError()

Enter a number: 2
Enter a number: 6
Enter a number: 3
Enter a number: 0

The Mean is: 3.6666666666666665

The Standard Deviation is : 2.0816659994661326


##### Lists
3 . Print the odd numbers from this list. `l = [2, 3, -2, -7, 0, 2, 3]`

In [3]:
# YOUR CODE HERE
l = [2, 3, -2, -7, 0, 2, 3]
for x in l:
    if x %2 != 0:
        result = x
        print(result)
# raise NotImplementedError()

3
-7
3


##### Functions
4 . Write a function that takes an integer parameter `(N)` and returns a list of the first `N` prime numbers starting from 2.

In [47]:
# YOUR CODE HERE
def is_prime(n):
    if n > 1:
        for i in range(2,n):
            if(n%i==0):
                return False
        return True

def get_n_primes(N):
    prime_numbers = []
    num = 2
    while len(prime_numbers) < N:
        if is_prime(num):
            prime_numbers.append(num)
        num += 1
    return prime_numbers
# raise NotImplementedError()

In [48]:
get_n_primes(5)

[2, 3, 5, 7, 11]

In [49]:
assert(get_n_primes(3) == [2, 3, 5])
assert(get_n_primes(0) == [])

5. Write a function that takes an integer parameter (N) and returns the Nth Fibonacci number.

 The Fibonacci series is defined as:

$$
F_n = F_{n-1} + F_{n-2} \text{ for } n>1\\
F_0 = 0\\
F_1 = 1
$$

The first few elements of the Fibonacci series are 0, 1, 1, 2, 3, 5, 8, 13 etc.

Raise a `ValueError` if $N<0$.


In [7]:
# YOUR CODE HERE
def get_nth_fibonacci(N):
    if N < 0:
        raise ValueError ('Enter a positive number')
    elif N == 0:
        return 0
    elif N == 1:
        return 1
    else:
        return get_nth_fibonacci(N-1)+get_nth_fibonacci(N-2)

# raise NotImplementedError()

In [11]:
print(get_nth_fibonacci(7))

13


In [9]:
assert(get_nth_fibonacci(0) == 0)
assert(get_nth_fibonacci(1) == 1)
assert(get_nth_fibonacci(2) == 1)
assert(get_nth_fibonacci(5) == 5)
assert(get_nth_fibonacci(7) == 13)

try:
    get_nth_fibonacci(-2)
except ValueError:
    pass
else:
    AssertionError("TEST FAILS. Negative index should raise a ValueError.")

6 . Create a function that take a list and a predicate (function with boolean return value) as parameters and returns a new list of those elements which the predicate return True. A predicate is a function that takes one element and return `True` or `False`, for example `is_even`, `is_prime`. If you implemented The following tests should run.


In [16]:
# YOUR CODE HERE
def is_odd(N):
    return N %2 != 0

def is_prime(N):
    if(N==1 or N==0):
            return False
        
    for i in range(2,N):
        if(N%i==0):
            return False
    return True

def filter_list(listx, predicate):
    filtered_list = []
    for i in listx:
        if predicate(i):
            filtered_list.append(i)
    return filtered_list
# raise NotImplementedError()

In [17]:
l1 = [1, 2, 3, 4, 19, 35, 11]
filter_list(l1, is_odd)

[1, 3, 19, 35, 11]

In [18]:
filter_list(l1, is_prime)

[2, 3, 19, 11]

In [19]:
l2 = [1, 4, 9, 16, 25]
filter_list(l2, is_prime)

[]

In [20]:
l1 = [1, 2, 3, 4, 19, 35, 11]
l2 = [1, 4, 9, 16, 25]
assert(filter_list(l1, is_odd) == [1, 3, 19, 35, 11])
assert(filter_list(l1, is_prime) == [2, 3, 19, 11])
assert(filter_list(l2, is_prime) == [])

7.  Reduce is a function that applies a two argument function against an accumulator and each element in the sequence (from left to right) to reduce it to a single value. If no initial value is provided, the accumulator is initialized with the return value of the function run on the first two elements of the sequence.

```
reduce([1, 2, 3], product) ---> 6
reduce([1, 2, 3], product, accumulator=10) ---> 60
reduce(["foo", "bar"], string_addition) ---> "foobar"
reduce(["foo", "bar"], string_addition, accumulator="hello") ---> "hellofoobar"
```

In [6]:
import numpy as np

In [20]:
# YOUR CODE HERE
def reduce(listX, func, accumulator=None):
    my_array = listX.copy()
    if accumulator is not None:
        return func(my_array) + accumulator
    else:
        return func(my_array)

def add(z):
    return np.sum(z)

def product(x):
    return np.product(x)

def string_len_add(z):
    result = "".join(z)
    print(result)
    return len(result)

def longest_string(list_of_strings):
    longest = ''
    for s in list_of_strings:
        if len(s) > len(longest):
            longest = s
    return longest

def count_odd_numbers(z):
    count = 0
    for i in z:
        if i %2 != 0:
            count += 1
    return count

# raise NotImplementedError()

In [12]:
l1 = [1, 2, -1, 5]
l2 = ["foo", "bar", "hello"]

assert(reduce(l1, add) == 7)
assert(reduce(l1, add, 10) == 17)
assert(reduce(l2, string_len_add, 0) == 11)

foobarhello


8. Use your reduce function for the following operations:

##### a. count the number of odd elements in a list of integers,
##### b. find the maximum of a list of integers,
##### c. find the longest string in list of strings.

``` Test your solutions. ```

In [41]:
# YOUR CODE HERE
print(reduce(l1, max))
# raise NotImplementedError()

5


In [46]:
# YOUR CODE HERE
print(reduce(l2, longest_string))
# raise NotImplementedError()

hello


In [23]:
print(reduce(l1, count_odd_numbers, 1))

4


9. Create a function that takes a matrix of size NxM and returns the pairwise L2 distance of each row pair.

For input $A^{N \times M}$, the output should be $D^{N \times N}$ where: $D_{i,j} = L_2 (A_i, A_j)$

In [58]:
# YOUR CODE HERE
def pairwise_row_distance(A):
    A = np.array(A, dtype=float)
    num_rows = A.shape[0]
    D = np.zeros((num_rows, num_rows), dtype=float)
    
    for i in range(num_rows):
        for j in range(num_rows):
            D[i][j] = np.sqrt(np.sum((A[i] - A[j]) ** 2))
    return D

def transpose(A):
    return A.T

# raise NotImplementedError()

In [60]:
D = pairwise_row_distance([[1, 0, 2], [0, 2, 1]])
# should be a matrix
# assert is_matrix(D) == True
assert len(D) == 2
assert len(D[0]) == 2
assert D[0][0] == 0
assert abs(D[0][1] - 2.449489742783178) < 1e-3
assert abs(D[1][0] - 2.449489742783178) < 1e-3
assert D[1][1] == 0

# should be symmetric
# assert transpose(D) == D

In [34]:
D

array([[0.        , 2.44948974],
       [2.44948974, 0.        ]])

10 . Object Oriented Programming
 Define a class named `A` with a 'constructor' that takes a single parameter and stores it in an attribute named `value`. Add a `print_value` method to the class. Instantiate the class and call the `print_value` method.

In [79]:
# YOUR CODE HERE
class A:
    def __init__(self, value):
        self.value = value
        
    def print_value(self):
        print(self.value)
a = A(2)
a.print_value()
# raise NotImplementedError()

2


In [80]:
a = A("abc")
a.print_value()

abc


11.  Define a class named `B`, whose `__init__` takes two parameters and stores one in a public attribute and the other in a private attribute named `this_is_public` and `__this_is_private` respectively. Check the class's ``__dict__``  attribute and find out the mangled name of the private attribute.

In [81]:
# YOUR CODE HERE
class B:
    def __init__(self, this_is_public, __this_is_private):
        self.this_is_public = this_is_public
        self.__this_is_private = __this_is_private


b = B(2022, 2023)
print(b.__dict__)
# raise NotImplementedError()

{'this_is_public': 2022, '_B__this_is_private': 2023}


In [82]:
b = B(1, 2)
assert b.this_is_public == 1
try:
    b.__this_is_private
    print("This should not happen.")
except AttributeError:
    print("Failed to access private attribute, this is good :)")

Failed to access private attribute, this is good :)


13 . Inheritance

###### Guess the output without running the cell.

In [ ]:
class A(object): pass
class B(A): pass
class C(A): pass
class D(B): pass

a = A()
b = B()
c = C()
d = D()

print(isinstance(a, object))   #True
print(isinstance(b, object))   #True
print(isinstance(a, B))        #False
print(isinstance(b, A))        #True
print(isinstance(d, A))        #True

In [ ]:
print(issubclass(C, object))   #True
print(issubclass(D, B))        #True
print(issubclass(B, D))        #False
print(issubclass(B, B))        #True

#### Create a Cat, a Dog, a Fish and a Eagle class.

The animals have the following attributes:

1. cats, dogs and eagles can make a sound (this should be a make_sound function that prints the animals sound),
2. all animals have an age and a number_of_legs attribute,
3. cats and dogs have a fur_color attribute. They can be instantiated with a single color or a list or tuple of colors.

Use inheritance and avoid repeating code. Use default values in the constructors.

In [25]:
# YOUR CODE HERE
class Animal:
    def __init__(self, age=0, number_of_legs=4):
        self.age = age
        self.number_of_legs = number_of_legs

    def make_sound(self):
        print("I have a sound")


class Cat(Animal):
    def __init__(self, age=0, number_of_legs=4, fur_color="white"):
        super().__init__(age, number_of_legs)
        self.fur_color = fur_color

    def make_sound(self):
        print("Meow")


class Dog(Animal):
    def __init__(self, age=0, number_of_legs=4, fur_color="white"):
        super().__init__(age, number_of_legs)
        self.fur_color = fur_color

    def make_sound(self):
        print("Woof")


class Fish(Animal):
    def __init__(self, age=0, number_of_legs=0):
        super().__init__(age, number_of_legs)

    def make_sound(self):
        print("Blub")


class Eagle(Animal):
    def __init__(self, age=0, number_of_legs=2):
        super().__init__(age, number_of_legs)

    def make_sound(self):
        print("Screech")


cat = Cat(age=10, fur_color="white")
print(cat.fur_color)
cat.make_sound()

dog = Dog(age=5, fur_color=["black", "white"])
print(dog.fur_color)
dog.make_sound()

fish = Fish(age=1)
fish.make_sound()

eagle = Eagle(age=2)
eagle.make_sound()

# raise NotImplementedError()

white
Meow
['black', 'white']
Woof
Blub
Screech


In [ ]:
try:
    cat = Cat("Fluffy", age=3, fur="white")
    dog = Dog("Cherry", age=1, fur=("white", "brown", "black"))
    fish = Fish("King")
    eagle = Eagle("Bruce", age=2)
    animals = [cat, dog, fish, eagle]
except Exception as e:
    print(f'Could not initialize an animal: {e}')

#### Numpy basic exercises

Use vectorization and avoid for loops in all exercises. Implement each exercise as a single function.

##### Implement standardization for 2D arrays.

Standardization is defined as:

\begin{equation*}
X_{std} = \frac{X - \mu}{\sigma},
\end{equation*}

where $\mu$ is the mean of each row and $\rho$ is the standard deviation of each column.

In [26]:
def standardize(X):
    # YOUR CODE HERE
    import numpy as np

def standardize(matrix):    
    mean = np.mean(matrix, axis=1)
    standard_deviation = np.std(matrix, axis=0)
    standard_matrix = (matrix - mean[:, np.newaxis]) / standard_deviation
    return standard_matrix

X_std = standardize(np.array([[1, 2], [2, 3], [1, 2]]))
X_std
# raise NotImplementedError()


array([[-1.06066017,  1.06066017],
       [-1.06066017,  1.06066017],
       [-1.06066017,  1.06066017]])

#### Implement normalization for 2D arrays.

Normalization is defined as:

\begin{equation*}
X_{norm} = \frac{X - X_{min}}{X_{max} - X_{min}}
\end{equation*}

In [53]:
def normalize(matrix):
    # YOUR CODE HERE
    min_value = np.min(X, axis=0)
    max_value = np.max(X, axis=0)
    normalized_matrix = (matrix - min_value) / (max_value - min_value)

    return normalized_matrix

X = np.arange(6).reshape(2, 3)
X[1, 2] = -5
print(X)
normalize(X)

[[ 0  1  2]
 [ 3  4 -5]]


array([[0., 0., 1.],
       [1., 1., 0.]])

In [54]:
answer = np.array(
    [[0., 0., 1.],
     [1., 1., 0.]]
)
X_norm = normalize(X)
assert np.allclose(X_norm, answer)